export const cadenceTableActions = Object.freeze({
  CADENCE_TABLE_CADENCE_LOADED: 'CADENCE_TABLE_CADENCE_LOADED',
  CADENCE_TABLE_CHANGE_TIMEWINDOW_FILTER: 'CADENCE_TABLE_CHANGE_TIMEWINDOW_FILTER',
  CADENCE_TABLE_DRILLDOWN_MONTH_TO_WEEK: 'CADENCE_TABLE_DRILLDOWN_MONTH_TO_WEEK',
  CADENCE_TABLE_DRILLDOWN_WEEK_TO_DAY: 'CADENCE_TABLE_DRILLDOWN_WEEK_TO_DAY',
  CADENCE_TABLE_LOAD_DATA: 'CADENCE_TABLE_LOAD_DATA',
  CADENCE_TABLE_LOAD_COMPANY_STATUS_COLORS: 'CADENCE_TABLE_LOAD_COMPANY_STATUS_COLORS',
  CADENCE_TABLE_UPDATE_POSITIONS: 'CADENCE_TABLE_UPDATE_POSITIONS',
  CADENCE_TABLE_GO_TODAY: 'CADENCE_TABLE_GO_TODAY',
  CADENCE_TABLE_SET_EXTRA_DAYS: 'CADENCE_TABLE_SET_EXTRA_DAYS',
  CADENCE_TABLE_REFRESH: 'CADENCE_TABLE_REFRESH',
});
