export const timeTableActions = Object.freeze({
  TIMETABLE_SET_ACTIVITIES_INBOUND: 'TIMETABLE_SET_ACTIVITIES_INBOUND',
  TIMETABLE_SET_COMPANY_STATUS_ACTIVITIES: 'TIMETABLE_SET_COMPANY_STATUS_ACTIVITIES',
  TIMETABLE_SET_OPPORTUNITY_STATUS_ACTIVITIES: 'TIMETABLE_SET_OPPORTUNITY_STATUS_ACTIVITIES',
});
