import FormControl from '@material-ui/core/FormControl';
import RadioGroup from '@material-ui/core/RadioGroup';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import Radio from '@material-ui/core/Radio';
import React from 'react';
import Grid from '@material-ui/core/Grid';
import Collapse from '@material-ui/core/Collapse';
import { options, steps } from '../../constants';
import { useImportForm } from '../../../../hooks/useImportForm';
import styles from './importOptionsSection.module.css';

const CustomFormRadioLabel = ({ value, label, selected, disabled }) => (
  <FormControlLabel
    classes={{
      root: selected ? styles.customFormLabel__selectedRoot : styles.customFormLabel__root,
      label: styles.customFormLabel__label,
    }}
    value={value}
    disabled={disabled}
    control={
      <Radio
        color={'secondary'}
        classes={{ colorSecondary: styles.customFormLabel__secondary }}
        icon={<span className={styles.customFormLabel__icon} />}
        checkedIcon={<span className={styles.customFormLabel__checkedIcon} />}
      />
    }
    label={label}
  />
);

const ImportOptionsSectionView = () => {
  const { step, action, setAction } = useImportForm();
  return (
    <React.Fragment>
      <Grid xs={12} container direction={'row'} alignItems={'center'} justify={'center'}>
        <Grid xs={9} item alignItems={'center'} justify={'center'}>
          <FormControl component="fieldset">
            <RadioGroup
              aria-label="import_option"
              name="import_option"
              value={action}
              onChange={e => setAction(e.target.value)}
            >
              <CustomFormRadioLabel
                selected={action === options.actions.CREATE}
                value={options.actions.CREATE}
                label={'Create new objects'}
              />
              <CustomFormRadioLabel
                selected={action === options.actions.UPDATE}
                value={options.actions.UPDATE}
                label={'Update existing objects'}
              />
              <CustomFormRadioLabel
                selected={action === options.actions.DELETE}
                value={options.actions.DELETE}
                label={'Delete existing objects'}
              />
            </RadioGroup>
          </FormControl>
        </Grid>
      </Grid>
      <Collapse
        in={
          step === steps.UPLOAD &&
          (action === options.actions.UPDATE || action === options.actions.DELETE)
        }
      >
        <Grid xs={12} container direction={'row'} alignItems={'center'} justify={'center'}>
          <Grid xs={9} container alignItems={'center'} justify={'flex-start'}>
            <p />
            <p className={styles.textBold}>Make sure the file you upload has a “ID" column.</p>
            <p className={styles.text}>
              What does this mean? This column and ID was generated by Bloobirds when you exported
              data. This ID will be used to recognize existing objects in Bloobirds that should be
              updated or deleted.
            </p>
          </Grid>
        </Grid>
      </Collapse>
    </React.Fragment>
  );
};

export default ImportOptionsSectionView;
