export const ACTIVITY_FIELDS_LOGIC_ROLE = Object.freeze({
  CADENCE: 'ACTIVITY__CADENCE',
  CALL_LEAD_PHONE_NUMBER: 'ACTIVITY__CALL_LEAD_PHONE_NUMBER',
  CALL_RECORD_URL: 'ACTIVITY__CALL_RECORD_URL',
  CALL_RESULT: 'ACTIVITY__CALL_RESULT',
  COMPANY: 'ACTIVITY__COMPANY',
  DIRECTION: 'ACTIVITY__DIRECTION',
  EMAIL_LEAD: 'ACTIVITY__EMAIL_LEAD',
  INBOUND_FORM_NAME: 'ACTIVITY__INBOUND_FORM_NAME',
  LEAD: 'ACTIVITY__LEAD',
  MEETING_RESULT: 'ACTIVITY__MEETING_RESULT',
  MESSAGE_BODY: 'ACTIVITY__MESSAGE_BODY',
  MESSAGE_SUBJECT: 'ACTIVITY__MESSAGE_SUBJECT',
  NOTE: 'ACTIVITY__NOTE',
  OPPORTUNITY: 'ACTIVITY__OPPORTUNITY',
  PITCH_DONE: 'ACTIVITY__PITCH_DONE',
  PITCH: 'ACTIVITY__PITCH',
  REPORTED: 'ACTIVITY__REPORTED',
  STATUS_TITLE: 'ACTIVITY__STATUS_TITLE',
  TIME: 'ACTIVITY__TIME',
  TYPE: 'ACTIVITY__TYPE',
  USER: 'ACTIVITY__USER',
  IS_PINNED: 'ACTIVITY__IS_PINNED',
});

export const ACTIVITY_TYPES_VALUES_LOGIC_ROLE = Object.freeze({
  STATUS: 'ACTIVITY__TYPE_STATUS',
  INBOUND: 'ACTIVITY__TYPE__INBOUND',
  NOTE: 'ACTIVITY__TYPE__NOTE',
  LINKEDIN: 'ACTIVITY__TYPE__LINKEDIN_MESSAGE',
  EMAIL: 'ACTIVITY__TYPE__EMAIL',
  CALL: 'ACTIVITY__TYPE__CALL',
  CADENCE: 'ACTIVITY__TYPE_CADENCE',
  MEETING: 'ACTIVITY__TYPE__MEETING',
});

export const PITCH_DONE_VALUES_LOGIC_ROLE = Object.freeze({
  NO: 'ACTIVITY__PITCH_DONE__NO',
  YES: 'ACTIVITY__PITCH_DONE__YES',
});

export const CALL_RESULTS_LOGIC_ROLE = Object.freeze({
  CORRECT_CONTACT: 'ACTIVITY__CALL_RESULT__CORRECT_CONTACT',
  APPROACH: 'ACTIVITY__CALL_RESULT__APPROACH',
  GATEKEEPER: 'ACTIVITY__CALL_RESULT__GATEKEEPER',
});

export const ACTIVITY_MODE = Object.freeze({
  CREATE: 'CREATE',
  EDIT: 'EDIT',
});

export const CADENCE_TYPES_VALUES_LOGIC_ROLE = Object.freeze({
  CONFIGURE: 'ACTIVITY__TYPE_CADENCE__CONFIGURED',
  ENDED: 'ACTIVITY__TYPE_CADENCE__ENDED',
  RESCHEDULE: 'ACTIVITY__TYPE_CADENCE__RESCHEDULE',
  STOPPED: 'ACTIVITY__TYPE_CADENCE__STOPPED',
});

export const TYPES_STATUS_VALUES_LOGIC_ROLE = Object.freeze({
  OPPORTUNITY_CREATED: 'ACTIVITY__TYPE_STATUS__OPPORTUNITY_CREATED',
  OPPORTUNITY_ASSIGNED: 'ACTIVITY__TYPE_STATUS__OPPORTUNITY_ASSIGNED',
  OPPORTUNITY_STATUS_CHANGED: 'ACTIVITY__TYPE_STATUS__OPPORTUNITY_STATUS_CHANGED',
  NEW_LEAD_CREATED: 'ACTIVITY__TYPE_STATUS__NEW_LEAD_CREATED',
  NEW_LEAD_ADDED_TO_OPPORTUNITY: 'ACTIVITY__TYPE_STATUS__NEW_LEAD_ADDED_TO_OPPORTUNITY',
});

export const REPORTED_VALUES_LOGIC_ROLE = Object.freeze({
  YES: 'ACTIVITY__REPORTED__YES',
  NO: 'ACTIVITY__REPORTED__NO',
});

export const ACTIVITY_TYPES = Object.freeze({
  CADENCE: 'Cadence',
  CALL: 'Call',
  EMAIL: 'Email',
  INBOUND: 'Inbound',
  LINKEDIN: 'LinkedIn Message',
  MEETING: 'Meeting',
  NOTE: 'Note',
  STATUS: 'Status',
});

export const ACTIVITY_DIRECTION = Object.freeze({
  INCOMING: 'Incoming',
  OUTGOING: 'Outgoing',
});
