export const COMPANY_STATUS = Object.freeze({
  ACCOUNT: 'ACCOUNT',
  CONTACTED: 'CONTACTED',
  DISCARDED: 'DISCARDED',
  ENGAGED: 'ENGAGED',
  MEETING: 'MEETING',
  NURTURING: 'NURTURING',
  ON_PROSPECTION: 'ON_PROSPECTION',
});

export const COMPANY_STATUS_LOGIC_ROLE = Object.freeze({
  ACCOUNT: 'COMPANY__STATUS__ACCOUNT',
  CONTACTED: 'COMPANY__STATUS__CONTACTED',
  DISCARDED: 'COMPANY__STATUS__DISCARDED',
  ENGAGED: 'COMPANY__STATUS__ENGAGED',
  MEETING: 'COMPANY__STATUS__MEETING',
  NURTURING: 'COMPANY__STATUS__NURTURING',
  ON_PROSPECTION: 'COMPANY__STATUS__ON_PROSPECTION',
  READY_TO_PROSPECT: 'COMPANY__STATUS__READY_TO_PROSPECT',
});

export const COMPANY_HIGH_PRIORITY_LOGIC_ROLE = Object.freeze({
  NO: 'COMPANY__HIGH_PRIORITY__NO',
  YES: 'COMPANY__HIGH_PRIORITY__YES',
});

export const COMPANY_FIELDS_LOGIC_ROLE = Object.freeze({
  ASSIGNED_TO: 'COMPANY__ASSIGNED_TO',
  ATTEMPTS_COUNT: 'COMPANY__ATTEMPTS_COUNT',
  ATTEMPTS_LAST_DAY: 'COMPANY__ATTEMPTS_LAST_DAY',
  AUTHOR: 'COMPANY__AUTHOR',
  CADENCE: 'COMPANY__CADENCE',
  COUNTRY: 'COMPANY__COUNTRY',
  HIGH_PRIORITY: 'COMPANY__HIGH_PRIORITY',
  LINKEDIN_URL: 'COMPANY__LINKEDIN_URL',
  MR_RATING: 'COMPANY__MR_RATING',
  NAME: 'COMPANY__NAME',
  SOURCE: 'COMPANY__SOURCE',
  START_CADENCE: 'COMPANY__START_CADENCE',
  STATUS: 'COMPANY__STATUS',
  TARGET_MARKET: 'COMPANY__TARGET_MARKET',
  TOUCHES_COUNT: 'COMPANY__TOUCHES_COUNT',
  TOUCHES_LAST_DAY: 'COMPANY__TOUCHES_LAST_DAY',
  WEBSITE: 'COMPANY__WEBSITE',
  CADENCE_STOPPED: 'COMPANY__CADENCE_STOPPED',
});
