export const LEAD_STATUS = Object.freeze({
  MEETING: 'MEETING',
  CONTACT: 'CONTACT',
  DISCARDED: 'DISCARDED',
});

export const LEAD_STATUS_LOGIC_ROLE = Object.freeze({
  CONTACT: 'LEAD__STATUS__CONTACT',
  CONTACTED: 'LEAD__STATUS__CONTACTED',
  DISCARDED: 'LEAD__STATUS__DISCARDED',
  ENGAGED: 'LEAD__STATUS__ENGAGED',
  MEETING: 'LEAD__STATUS__MEETING',
  NURTURING: 'LEAD__STATUS__NURTURING',
  ON_PROSPECTION: 'LEAD__STATUS__ON_PROSPECTION',
});

export const LEAD_FIELDS_LOGIC_ROLE = Object.freeze({
  ATTEMPTS_COUNT: 'LEAD__ATTEMPTS_COUNT',
  ATTEMPTS_LAST_DAY: 'LEAD__ATTEMPTS_LAST_DAY',
  AUTHOR: 'LEAD__AUTHOR',
  COMPANY: 'LEAD__COMPANY',
  DISCARDED_REASONS: 'LEAD__DISCARDED_REASONS',
  FULL_NAME: 'LEAD__FULL_NAME',
  ICP: 'LEAD__ICP',
  JOB_TITLE: 'LEAD__LINKEDIN_JOB_TITLE',
  LINKEDIN_JOB_TITLE: 'LEAD__LINKEDIN_JOB_TITLE',
  NAME: 'LEAD__NAME',
  NURTURING_REASONS: 'LEAD__NURTURING_REASONS',
  OPPORTUNITY: 'LEAD__OPPORTUNITY',
  PHONE: 'LEAD__PHONE',
  STATUS: 'LEAD__STATUS',
  TOUCHES_COUNT: 'LEAD__TOUCHES_COUNT',
  TOUCHES_LAST_DAY: 'LEAD__TOUCHES_LAST_DAY',
});
