export const OPPORTUNITY_FIELDS_LOGIC_ROLE = Object.freeze({
  AMOUNT: 'OPPORTUNITY__AMOUNT',
  ASSIGNED_TO: 'OPPORTUNITY__ASSIGNED_TO',
  ATTEMPTS_LAST_DAY: 'OPPORTUNITY__ATTEMPTS_LAST_DAY',
  AUTHOR: 'OPPORTUNITY__AUTHOR',
  CADENCE_STOPPED: 'OPPORTUNITY__CADENCE_STOPPED',
  CADENCE: 'OPPORTUNITY__CADENCE',
  CLOSE_DATE: 'OPPORTUNITY__CLOSE_DATE',
  COMPANY: 'OPPORTUNITY__COMPANY',
  CREATION_DATE: 'OPPORTUNITY__CREATION_DATE',
  NAME: 'OPPORTUNITY__NAME',
  START_CADENCE: 'OPPORTUNITY__START_CADENCE',
  STATUS__CLOSED_LOST: 'OPPORTUNITY__STATUS__CLOSED_LOST',
  STATUS__CLOSED_WIN_DATE: 'OPPORTUNITY__STATUS__CLOSED_WIN_DATE',
  STATUS__CLOSED_WIN: 'OPPORTUNITY__STATUS__CLOSED_WIN',
  STATUS__LAST_UPDATE: 'OPPORTUNITY__STATUS__LAST_UPDATE',
  STATUS: 'OPPORTUNITY__STATUS',
});

export const OPPORTUNITY_STATUS_LOGIC_ROLE = Object.freeze({
  CLOSED_LOST: 'OPPORTUNITY__STATUS__CLOSED_LOST',
  CLOSED_WON: 'OPPORTUNITY__STATUS__CLOSED_WON',
});
