export const TASK_TYPE = Object.freeze({
  ADD_LEADS_TO_QC: 'ADD_LEADS_TO_QC',
  CONTACT_BEFORE_MEETING: 'CONTACT_BEFORE_MEETING',
  MEETING: 'MEETING',
  NEXT_STEP: 'NEXT_STEP',
  PROSPECT_CADENCE: 'PROSPECT_CADENCE',
  START_CADENCE: 'START_CADENCE',
});

export const TASK_STATUS_VALUE_LOGIC_ROLE = Object.freeze({
  COMPLETED: 'TASK__STATUS__COMPLETED',
  TODO: 'TASK__STATUS__TODO',
  OVERDUE: 'TASK__STATUS__OVERDUE',
});

export const TASK_FIELDS_LOGIC_ROLE = Object.freeze({
  ASSIGNED_TO: 'TASK__ASSIGNED_TO',
  COMPANY: 'TASK__COMPANY',
  LEAD: 'TASK__LEAD',
  OPPORTUNITY: 'TASK__OPPORTUNITY',
  SCHEDULED_DATE: 'TASK__SCHEDULED_DATE',
  SCHEDULED_DATETIME: 'TASK__SCHEDULED_DATETIME',
  STATUS: 'TASK__STATUS',
  TASK_TYPE: 'TASK__TASK_TYPE',
  TITLE: 'TASK__TITLE',
});

export const TASK_MODE = Object.freeze({
  CREATE: 'CREATE',
  EDIT: 'EDIT',
});
